from __future__ import annotations

from typing import Any


EXPECTED_CLIENT_ASSET_MAPPING: dict[str, str | dict[str, Any]] = {
    "@timestamp": "date",
    "asset": {
        "acr_score": "long",
        "agent_id": "text",
        "environment": "text",
        "external": "text",
        "host_tag": "text",
        "id": "text",
        "importance": "text",
        "importance_code": "long",
        "in_inventory": "boolean",
        "ip": "text",
        "last_scan_date": "date",
        "last_scan_status": "text",
        "name": "text",
        "os": "text",
        "owner": "text",
        "private_ip": "text",
        "qwebhost_id": "text",
        "rsa_score": "long",
        "score": "long",
        "status": "text",
        "tags": "text",
        "type": "text",
        "url": "text",
        "userEmail": "text",
    },
    "asset_events": {
        "cis_name": "text",
        "compliance": {
            "fail": "long",
            "invalid": "long",
            "pass": "long",
            "score": "long",
            "total_checks": "long",
        },
        "id": "text",
        "last_scan_status": "text",
        "lastcheckedin": {"days_since": "text"},
        "method": "text",
        "technology": "text",
    },
    "asset_vuln": {
        "asset_id": "text",
        "installed_software": {"quantity": "long"},
        "key": "text",
        "last_scan_status": "text",
        "lastcheckedin": {"days_since": "long"},
        "mandatory_missing": {"quantity": "long"},
        "method": "text",
        "technical_specs": {
            "bios_description": "text",
            "last_loggedon_user": "text",
            "processor": {"name": "text", "speed": "text"},
            "total_memory": "text",
        },
        "technology": "text",
        "unauthorized_installed": {"quantity": "long"},
        "users": "text",
    },
    "client": "text",
    "technology": "text",
}
